### ISSUE TITLE
Multi CPU

### ISSUE THREAD

**Issue by bilalY** [spdermn02/TouchPortal_OpenHardwareMonitor_Plugin#19]
Hi is there any way to show multi CPU systems with this plugin? 

Hardware Monitor shows both CPUs. combined i have 16 cores.

**Comment by spdermn02** [comment]
I suppose I could add some logic for this. A lot of this is hard for me to know exactly since I don't have a multi-cpu system. I think I need to do some rework to make this plugin "smarter" as right now a lot is config but hard coded config. Being able to determine and add states on the fly would be awesome.

**Comment by bilalY** [comment]
thanks for getting back to me. if and when you decide to work on what you proposed, I'm happy to help in any way I can.

**Comment by spdermn02** [comment]
I'm working on rewritting this completely using Node.JS and completely different through process, so all hardware found by Open Hardware Monitor (or Libre Hardware Monitor) will create their own categorized states and be usable. So no more  set list of data, it will be all dynamic and work for whatever your hardware config is. Release date is TBD though. need to prioritize it onto my free time list.

**Comment by spdermn02** [comment]
Sorry this took forever - but multi-cpu support is now available in the rewritten plugin - https://github.com/spdermn02/TouchPortal-HardwareMonitor - it is completely different configuration, and i recommend using Libre Hardware Monitor as their development is more active than OHM was.
